### ISSUE TITLE
Hardcoded default SAI slot

### ISSUE THREAD

**Issue by pepfof** [STMicroelectronics/stm32h747i-disco#5]
https://github.com/STMicroelectronics/stm32h747i-disco-bsp/blob/bb81c6532fcc301fc760a98f8a42acede46bea83/stm32h747i_discovery_audio.c#L282

SAI active slot is set appropriately for headphone output, regardless of audioinit device selection. I was not able to get output on the speaker ports without changing this to the appropriate codec slot for speaker/spk+hp.

Any reason this shouldn't be chosen automatically based on AudioInit->Device ..?

Thank you.

**Comment by KRASTM** [comment]
Hello @pepfof,

Thank you for the report.

In fact, there is two functions, one for the BSP_AUDIO_OUT_Init() and the other for BSP_AUDIO_IN_Init(), also there is a list of SAI Slot that must be activated for type of audio stream, below an extract from the header file:
https://github.com/STMicroelectronics/stm32h747i-disco-bsp/blob/bb81c6532fcc301fc760a98f8a42acede46bea83/stm32h747i_discovery_audio.h#L185-L199

In addition, there is an example BSP under `\Projects\STM32H747I-DISCO\Examples\BSP\EWARM` that contain 2 Demos, `AudioPlay_demo and AudioRecord_demo` for this board, but unavailable on this repository as mentioned on the readme file, because they `are subject to some restrictive license terms requiring the user's approval via a "click thru" procedure.`

However, you can download the [package](https://www.st.com/en/embedded-software/stm32cubeh7.html#get-software), and you can check it for more details.

I hope this may help you.

With regards,

**Comment by pepfof** [comment]
Hi @KRASTM,

Yes, thank you for this note, but my question/suggestion was - why is CODEC_AUDIOFRAME_SLOT_02 hardcoded in BSP_AUDIO_OUT(IN)_Init? 

We pass the device(s) we want to activate through the init struct to these functions, shouldn't they infer from this the codec slot to use? 

If this is done, it would be sufficient to only change the device in the init structure, and you wouldn't have to change BSP code in multiple places just to change the audio device... 

Besides, the way the current code is written doesn't allow the user to use different devices subsequently (without not-insignificantly rewriting bsp code)

Regards

**Comment by KRASTM** [comment]
Hello @pepfof,

I shared your idea with our team, apparently it is related to a specific configuration and a choice from the developer, that's why the slot is hardcoded in the 2 functions.

I concur with your recommendation, but unfortunately, there is no plan to update BSP driver in the short term. I will keep you informed if there are any updates. Please allow me to close this issue.

Thank you in advance for your comprehension.

With regards.

**Comment by pepfof** [comment]
Hi @KRASTM,

OK, thank you.
